### ISSUE TITLE
Use Configuration system to get App Insights instrumentation key

### ISSUE THREAD

**Issue by anurse** [aspnet/AzureIntegration#102]
Right now, our HostingStartup calls `.UseApplicationInsights()`, which triggers the magic Instrumentation Key look-up that AI does here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/f696dd44f55055fad1774154219acf6c1e32c99b/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L29

However, if you are deploying to some environment other than Azure Web Apps, you may want to store the instrumentation key elsewhere. For example, in a Docker swarm, you'd want to use Docker Secrets. Since AI pulls the instrumentation key from configuration by setting up it's own providers, this doesn't work. The Hosting Startup could solve this by reading out of the Configuration (via `WebHostBuilderContext`) that the user configured, thus allowing all the user's custom configuration providers to have a chance to provide the Instrumentation Key.

As we build out a diagnostics infrastructure, we may end up with a well-defined configuration structure for Diagnostics/Metrics providers, like we have for Logging, so we should keep that in mind when figuring out where to read the Instrumentation Key from in config (obviously we'll need back-compat and support for how Azure Web Apps sets it as well).

/cc @pakrym

**Comment by muratg** [comment]
@pakrym will take a look at this.

**Comment by muratg** [comment]
AppInsights owns their own hosting startup stuff.
