### ISSUE TITLE
Build site extensions package to consume latest runtime and ASP.NET Core

### ISSUE THREAD

**Issue by pakrym** [aspnet/AzureIntegration#105]
Almost same thing as test bundle but without install script that copies old runtime.
Also we need a feed to push it too, this feed should also have ASP.NET packages that are included in site extensions.

**Comment by muratg** [comment]
Let's give this a shot 🤞

**Comment by muratg** [comment]
cc @shirhatti who will be adding the ANCM instructions here.

**Comment by glennc** [comment]
Taking this issue as the one that tracks getting the site extension ready to be used to deploy preview1. That was the intent right?

**Comment by glennc** [comment]
Clarifying intent for anyone reading this. As of ASP.NET Core 2.1 Preview1 we want to use App Service site extensions as the way to acquire the preview, as apposed to installing it globally on all Azure App Service machines.

This means that App Service only ever has RTM releases installed, not previews. To get a preview you would install the appropriate version of this extension.

The extension will carry ANCM as well as .NET Core.

**Comment by pakrym** [comment]
Blocked on https://github.com/dotnet/corefx/issues/25803

**Comment by pakrym** [comment]
Some notes on current implementation:

1. Site extension would not uninstall if the site is running because site is locked
2. The first-time experience is enabled by site extension but not forced during install to prevent time-outs. It will run the first time you use cli command (during git deploy)
3. We need to keep site extension name short because packages in NugetFallbackFolder exceed max path if used with a name like `Microsoft.AspNetCore.Runtime.SiteExtension`
