### ISSUE TITLE
Write code to detect an ASP.NET Core and ASP.NET application

### ISSUE THREAD

**Issue by glennc** [aspnet/AzureIntegration#109]
It should be able to accept a file path and return some information about the app, at least whether or not it is an ASP.NET or ASP.NET Core app.

**Comment by Tratcher** [comment]
I assume this is a standalone component? What's the TFM? This is for AI's site extension in Azure, correct? If so then the TFM should be NET461.

**Comment by muratg** [comment]
@pakrym Any thoughts on this?  What would be a way to do this reliably?

**Comment by muratg** [comment]
That's a good point -- @glennc what kind of reliability we want on this one?  Is it OK to sometimes misclassify a .NET Core app as a .NET app?  Or reverse is preferable?

**Comment by glennc** [comment]
It is expected that it will not necessarily be 100% accurate. The intent is that we can do things like:

1. Run logic to show ANCM startup errors in the portal only when using ASP.NET Core
2. Show banners to lightup App Insights only when using .NET or .NET Core

@davidebbo might be best placed to talk about what TFM we should target in the app. I think the intent is that we effectively give him the code and he makes it available to parts of the portal via an API.

**Comment by pakrym** [comment]
> 1. Run logic to show ANCM startup errors in the portal only when using ASP.NET Core
Why not detect presents of ANCM? It's very easy by just looking at web.config

**Comment by davidebbo** [comment]
I think detecting ANCM is a good start. Though it misses out on one key thing: the version on Core being used. Seems that this could be useful to have for the caller on the new API.

**Comment by pakrym** [comment]
@davidebbo additional information can be retrieved by looking at `deps` and `runtimeconfig` files.

**Comment by davidebbo** [comment]
Yep, that seems easy enough to go after. e.g. I see deps has:

```
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0",
    "signature": "aaef1231b5987f15e14d5e06e73e386cac8b3e66"
  },
```

And runtimeconfig has:

```
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
```

For my information, what's the difference between those two files, in term of conveying framework version?

**Comment by pakrym** [comment]
`runtimeTarget` in deps file controls which branch of targets to read, `runtimeOptions` `framework` controls shared runtime to run on.

**Comment by muratg** [comment]
related: #54
