### ISSUE TITLE
Proposal: Lightup packages configuration scheme

### ISSUE THREAD

**Issue by pakrym** [aspnet/AzureIntegration#110]
The only way to disable light up packages right now is to disable hosting startup support all together.  (https://github.com/aspnet/Home/issues/2051#issuecomment-318513988)

This proposal tries to spec the pattern to be used for current or future light up packages to enable user to control light-up feature in individual manner.

### Configuration source: 
Light up should use environment variable configuration source with `ASPNETCORE_` prefix + whatever was configured by user using `builder.ConfigureAppConfiguration` callback, this allows for two things:

1. Environment variables are always accessible even if `builder.ConfigureAppConfiguration` was used to remove environment variable provider.
2. `appsettings.json` and other common configuration mechanisms can be used to control ligthup.

Code sample:
``` C#
  builder.ConfigureServices((context, collection) =>
                {
                    var configuration = new ConfigurationBuilder()
                        .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                        .AddConfiguration(context.Configuration)
                        .Build();

                        .... use configuration 
                });
```

*NOTE:* for cases where `context.Configuration` is not accessible (for example if ligthup adds configuration provider) only environment variables should be used.

### Configuration schema:

Each component of lightup (read each extension method call) should be controlled by a configuration key. If value is not present it is defaulted to `true`. 

``` json
{
    "HostingStartup":{
        "ApplicationInsights": {
            "Logger" : true,
            "TagHelper": true
        },
        "KeyVault": {
            "Configuration": true,
            "DataProtection": true,
            "IdentityServer": true,
 
            "Vault": "http://keyvault.azure....",
            "DataProtectionKey": "KeyName",
            "IdentityCertificate": "CertificateName"
        },
        "AppServices":
        {
            "Logger": true
        }
    }
}
```

Same values as environment variables (using `ASPNETCORE_` prefix):
```
ASPNETCORE_HOSTINGSTARTUP__APPLICATIONINSIGHTS__LOGGER=TRUE
ASPNETCORE_HOSTINGSTARTUP__APPLICATIONINSIGHTS__TAGHELPER=TRUE
...
```

`true/false/1/0` are supported as values (case insensitive).

Common code to read these values would be extracted into source package in `AzureIntegration ` repo.

No configuration reading code should ever throw.

/cc @DamianEdwards @glennc @danroth27 @davidfowl @anurse

**Comment by Tratcher** [comment]
Side note: "ASPNETCORE_" env vars are already baked in.
https://github.com/aspnet/Hosting/blob/159a5f777ef932e1a8ebff3989080b1d7f621369/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L46

This proposal seems contrary to the intent of lightup components. These components are being provided by your environment, your app isn't supposed to know or care about them. If people want to opt into or out of the these components then that knob should be surfaced by the environment that's adding them. E.g. VS, Azure portal, etc..

**Comment by pakrym** [comment]
@Tratcher user can remove env vars provider in configureAppConfiguration callback: https://github.com/aspnet/Hosting/blob/159a5f777ef932e1a8ebff3989080b1d7f621369/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L251

**Comment by pakrym** [comment]
I removed per hosting startup `Enable` switches and changes `lighup` to `hostingstartup`. 

Use case for opting out of the feature:
https://github.com/aspnet/AzureIntegration/issues/88

Use case for configuration values:
https://github.com/aspnet/AzureIntegration/issues/102

**Comment by Tratcher** [comment]
AppServices only has the logger, correct? So that config value is the same as adding / removing the site extension.

**Comment by pakrym** [comment]
@Tratcher yeah, AppServices is here to serve as example of the pattern then actual useful flag.

**Comment by Tratcher** [comment]
Next we need to figure out where these values will actually be specified. It's unlikely to be a config file as the presence of these features is deployment / environment specific. Env vars are the most likely vector as that's how the lightup packages are added.

**Comment by muratg** [comment]
Closing this for now.
