### ISSUE TITLE
SiteExtension: Use ProgramFiles(x86) instead of ProgramFiles

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AzureIntegration#115]
https://github.com/aspnet/AzureIntegration/blob/9b9bb4dde7e9fa1bcfb31019ba9453882e1a318f/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/applicationHost.xdt#L10

The current extension uses the dynamic env var `%ProgramFiles%` to resolve the dotnet install directory. However, if you toggle your Platform to 64-bit then the value of this var changes from `d:\Program Files (x86)\` to `d:\Program Files\` which does not contain dotnet or deps.

Use `%ProgramFiles(x86)%` instead so we always point at the right directory.

This isn't breaking anything yet because we don't actively rely on the additional deps right now, but we are adding new components that will.

**Comment by muratg** [comment]
Since 2.1, we're not using Program Files folders for additional deps. Instead we carry them with the package. Shouldn't be a an issue now that 2.0 is dead.
