### ISSUE TITLE
SiteExtensionsTests: Update tests to target netcoreapp2.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AzureIntegration#120]
The tests are designed so that they the only work if @pakrym touches them. I'll leave it to him to do the needful.

**Comment by pranavkm** [comment]
cc @muratg \ @pakrym so we don't miss this

**Comment by Eilon** [comment]
@muratg / @pakrym - anything to do here for preview1?

**Comment by pakrym** [comment]
No, I guess we'll fix them for preview2.

**Comment by Eilon** [comment]
@muratg please do the needful.

**Comment by muratg** [comment]
Removing from preview2.  We'll look back into this after preview2.

**Comment by muratg** [comment]
Moved further out based on the scheduling realities. If we do end up getting some free time, we'll get to it before.

**Comment by natemcmaster** [comment]
Incidentally resolved with #254
