### ISSUE TITLE
AzureAppServices no longer implies IIS

### ISSUE THREAD

**Issue by glennc** [aspnet/AzureIntegration#13]
Today the UseAzureAppServices method implies IIS, and as such calls UseIISIntegration. With Linux Azure App Services that is no longer true.

We should consider removing UseIISIntegration from the UseAzureAppServices extension method.

**Comment by Tratcher** [comment]
~~consider~~ We decided today to remove UseIISIntegration from UseAzureAppServices.

**Comment by Tratcher** [comment]
https://github.com/aspnet/AzureIntegration/pull/15
