### ISSUE TITLE
Cannot edit file in Kudu Console due to 409 Conflict.

### ISSUE THREAD

**Issue by ndreisg** [aspnet/AzureIntegration#132]
Hello there,

in my Azure app I have a JSON file that should be editable at runtime.
Editing works fine as long as i do not make any mistakes in the JSON string.

As soon as a enter any invalid JSON I have the following problem:

When the app reads the file the next time, an exception is thrown and written to log stream. When I then try to correct the wrong json in the file, I get the following error:

`409 Conflict: Could not write to local resource 'D:\home\site\wwwroot\messages.json' due to error 'The process cannot access the file 'D:\home\site\wwwroot\messages.json' because it is being used by another process.'.`

Here is my code that reads and parses the file:

```
private static void UpdateInfoMessages()
{
  string path = "./messages.json";
  try
  {
    if (File.Exists(path) && File.GetLastWriteTime(path) >= lastInfoMessagesUpdate)
    {
      string fileContent = File.OpenText(path).ReadToEnd();
      infoMessages = JsonConvert.DeserializeObject<IEnumerable<InfoMessage>>(fileContent);
      lastInfoMessagesUpdate = DateTime.Now;
    }
  }
  catch (Exception e)
  {
    _logger.LogError(e, "InfoMessages could not be read: ");
    throw e;
  }
}
```

I don't really understand why I only get the error when the JSON is invalid. The "File.OpenText(path).ReadToEnd()" operation should run before the exception and should be successfully completed in both cases.

Did I miss anything? Is it possible to avoid this file lock or to unlock the file again?

BTW: I'm not sure if this is only related to .net Core or a genaral issue.

best regards 
Alex

**Comment by ndreisg** [comment]
I just realized, that the problem is not only when the JSON is invalid. Actually it happens always when I edit the file in KUDU Console and then my app reads the file. When I then try to edit it again, the error happens.

**Comment by ndreisg** [comment]
Not sure if this problem is caused by my App or by KUDU...
I'll try the same thing now over FTP.

**Comment by muratg** [comment]
@ndreisg Make sure to dispose the `StreamReader` coming from `File.OpenText(path)`.  This potentially is keeping the file locked for you.
