### ISSUE TITLE
Enable ETW logger by default on App Service via our site extension

### ISSUE THREAD

**Issue by muratg** [aspnet/AzureIntegration#134]
Should help customers with diagnostics.

**Comment by muratg** [comment]
cc @DamianEdwards @glennc

**Comment by DamianEdwards** [comment]
Some background from internal conversation:

> I work with the Diagnostics team of Azure App Service and we wanted to provide customers a way to collect ETW traces (something that Perfview understands today) for ASP.NET Core apps. We already can collect ETW traces for ASP.NET classic apps, analyze them and find issues and we want to basically do the same for ASP.NET Core apps.
> I understand that today for ETW to be emitted for an ASP.NET Core app, an end customer must do two things:
>1.	Add call to `logging.AddEventSourceLogger();`
>2.	Install the `Microsoft.Extensions.Logging` component via NuGet.
>
>Without this, I understand ETW events won’t be emitted. But this basically means that the customer must change this code and do a redeployment. Something that is not totally favorable for an end customer who is already hosting their app on Azure App Service. 
>
> Just like the App Services Integration package for ASP.NET Core for we Azure App Service (where we allow customer to just toggle the tracing switch in the portal) are we thinking of a way to make the emission of the ETW events easier? Basically, something that causes an ASP.NET Core app to just emit logs to ETW without modifying the customer code?
>
> I vaguely recall in some talks that Damian mention that we are working on some feature that allows us to dynamically inject modules or middleware and this might be possible with that help of that feature. Is that something that is ready and can be used here?

**Comment by muratg** [comment]
@DamianEdwards @glennc triage?

**Comment by puneetg1983** [comment]
Validated that the correct set of events are getting captured in the ETW trace that we collected on Antares using the Visual Studio diagnostic agent.

For all the ETW events to come in the ETW trace, I had to do two things.
1.	Make sure that we had call to `logging.AddEventSourceLogger` in the Program.cs
2.	Make sure that the default LogLevel in **appsettings.json** was set to Information like this

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information"
    }
  }
}
```

By default, this file has LogLevel, Default value of Warning and this was preventing all the events to be emitted to the trace

Would like to know if the site extension on Antares can enable all events by default and would it depend on what an end customer has set in his appsettings.json file or not.

For sake of completeness, putting the StartTracing and StopTracing commands that you can run from KUDU.

_**Start.BAT**_
`"D:\Program Files\Microsoft Visual Studio 15.0\Team Tools\DiagnosticsHub\Collector\VSDiagnostics.exe" start 88 /scratchLocation:"%LOCAL_EXPANDED%" /loadAgent:31003EE3-A8E1-427A-931E-97057D4D2B7D;ServiceProfilerAgent.dll`
`"D:\Program Files\Microsoft Visual Studio 15.0\Team Tools\DiagnosticsHub\Collector\VSDiagnostics.exe" update 88 /attach:%1 /loadAgent:F5091AA9-80DC-49FF-A7CF-BD1103FE149D;ServiceProfilerAgent.dll`
`"D:\Program Files\Microsoft Visual Studio 15.0\Team Tools\DiagnosticsHub\Collector\VSDiagnostics.exe" postString 88 "AddProvider:3ac73b97-af73-50e9-0822-5da4367920d0:0xFFFFFFFFFFFFFFFF:5" /agent:F5091AA9-80DC-49FF-A7CF-BD1103FE149D`

**_STOP.BAT_**
`"D:\Program Files\Microsoft Visual Studio 15.0\Team Tools\DiagnosticsHub\Collector\VSDiagnostics.exe" stop 88 /output:"%LOCAL_EXPANDED%\Temp\aribitraryFileName`

**Comment by glennc** [comment]
@puneetg1983 did you expect the loglevel in the portal to impact this or that it would give you all information all the time? The only loggers that honor what is in the portals Diagnostics Logs blade today are the file and blob storage logger that we just to handle those two parts of that blade.

What gesture do you expect a user to do in order to enable the ETW logs? From your scenario it sounds like you want to be able to do something to the site that automatically starts logging as much information as can be logged into ETW for your analysis and then turn it off. Is that correct?

**Comment by puneetg1983** [comment]
To add to it, we have the ability in azure app service to collect etw for IIS and classic ASP.net by using visual studio diagnostic agents which just expect the right provider guide, verbosity levels and keywords. The same mechanism can be used to collect etw for ASP.net core but the app has to emit the event at least for those mechanisms to catch it...

**Comment by glennc** [comment]
You don't have to convince me. I just want to understand what mechanisms we need. What do you expect users to do in order to turn it on?

**Comment by puneetg1983** [comment]
I see :-) 

All we need is .net core apps to emit ETW events without making any changes.

As of today, in Azure App Service, an end user can go to the KUDU console and collect a ETW trace for a process. When they click the start profiling button, we start the trace session for them and we enable the right providers. Once they have reproducted the issue, they can stop the session when they stop the session. Similar functionality exists in another place called Diagnostic as a Service.

![image](https://user-images.githubusercontent.com/5299838/37223051-4d7e2e94-23f5-11e8-8109-a4bff9c562be.png)


We want the similar experience.  We can code that button to enable the provider for Microsoft.web.Extensions in the background after checking if the process is a .net core process.

all we need is that the asp.net core app should always emit ETW events...

if required, we can control the verbosity and level by the trace session that we start ourselves..

**Comment by glennc** [comment]
And the information from https://github.com/aspnet/Hosting/blob/7890fdbf94df7463047ba05865b8f515d029e057/src/Microsoft.AspNetCore.Hosting/Internal/HostingEventSource.cs isn't enough so you want the EventSourceLogger info as well? AFAIK we always call the HostingEventSource commands if it's enabled.

The other logs that honor the loglevel from the appsettings.json you are showing go through the logging system. We can add the ETW source for people that use the app services site extension, as you have in your app. But the information is generally different. The logs from the logging system would include all application and framework logs as well as just hosting info. Does all of that information help you as well?

I want to explore what information you need. If the answer is "everything we can possibly get" then that's cool and we can go from there. But if it isn't that then I want to understand exactly what it is.

**Comment by puneetg1983** [comment]
everything we can possibly get in ETW

🙂

If required, let's talk to finish any remaining ends. Let me know

**Comment by puneetg1983** [comment]
Hi Everyone, any updates regarding this ?

**Comment by shirhatti** [comment]
I spent some time looking into this. Here’s my recommendation
- Use the existing Microsoft.AspNetCore.AzureAppServices.HostingStartup package (this will save the burden of figuring out additional deps)
- Use HostingStartup to inject to the EventSourceLogger (It’s already part of the shared framework, so it doesn’t bring in other dependencies)
- Also use HostingStartup to add a filter to turn down the log level to Informational for just the EventSourceLogger

Open questions:
- Do you want a way to control Log Level for the EventSourceLogger. I’m thinking just an on/off will suffice.
- How do we control turning of/off the EventSourceLogger? (For context, for other logger settings in our App Services integration package are controlled via D:\home\site\diagnostics\settings.json)
- Can we phase this into a 2.1.x patch?

**Comment by shirhatti** [comment]
Based on our meeting earlier today:
- We probably don't want to configure LogLevel for the EventSourceLogger. If an individual customer wants to, they can always add a logging filter
- Let's add an environment variable to turn off adding the EventSourceLogger for folks who find it too verbose.
- Unless Antares makes a concerted push for this, we aren't going to patch this in 2.1. This will only be a 2.2 feature.

@muratg @glennc @davidebbo @dariagrigoriu In case I missed something from our discussion

**Comment by pakrym** [comment]
Enabled for all apps https://github.com/aspnet/MetaPackages/pull/287
