### ISSUE TITLE
Move Microsoft.AspNetCore.KeyVault.HostingStartup to 2.0 patch branches

### ISSUE THREAD

**Issue by danroth27** [aspnet/AzureIntegration#137]
Currently Microsoft.AspNetCore.KeyVault.HostingStartup targets 2.1. The proposal here is to retarget it to 2.0 and ship it out of band on NuGet in alignment with 15.7.

**Comment by muratg** [comment]
cc @pakrym

**Comment by davidfowl** [comment]
What happens when you're a 2.1 application.

**Comment by Eilon** [comment]
So is this bug in the wrong milestone? This is intended for March 2018 == 2.0.6 patch?

**Comment by pakrym** [comment]
This is for connected services tooling support. Required for 15.7 preview3

**Comment by Eilon** [comment]
Sure, but is this supposed to go into the March 2018 patch train build?

**Comment by pakrym** [comment]
Done in https://github.com/aspnet/AzureIntegration/pull/156
