### ISSUE TITLE
Unable to install this package on my netcoreapp v 1.1

### ISSUE THREAD

**Issue by Lutando** [aspnet/AzureIntegration#14]
I get the following when trying to install `Microsoft.AspNetCore.AzureAppServicesIntegration` into my aspnet core application. Simple steps to reproduce

1) File new project aspnet core 
2) Add `Microsoft.AspNetCore.AzureAppServicesIntegration` 

![image](https://cloud.githubusercontent.com/assets/1838141/24470617/e202fad6-14bf-11e7-9c4a-628dcf03a234.png)

**Comment by GuardRex** [comment]
@Lutando Specify the `<PackageTargetFallback>` in your `csproj`, which will allow those packages to work.

```xml
<PropertyGroup>
  <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8;portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
</PropertyGroup>
```

**Comment by Lutando** [comment]
Thanks a bunch :)
