### ISSUE TITLE
AppModelDetector.Detect returns DotNetFramework for nondeterministic / empty folder

### ISSUE THREAD

**Issue by soninaren** [aspnet/AzureIntegration#140]
Can we add default return type to be Unknown or something similar in case it is nondeterministic?

**Comment by pakrym** [comment]
What are the criteria to categorize folder as the desktop framework?

**Comment by soninaren** [comment]
I am not sure how can that be determined.
But right now the API is returning DotNet Framework for anything that is not DotNetCore or DotNetCoreStandalone. For now i figured it would be nice have that fixed.

**Comment by pakrym** [comment]
I would be glad to do changes but we have to decide on rules/scenarios of what we detect as nondeterministic

**Comment by soninaren** [comment]
As if now to me, Anything that cannot be categorized as DotNetCore or DotNetCoreStandalone would fall under nondeterministic category.

**Comment by muratg** [comment]
We don't expect to do any changes here.
