### ISSUE TITLE
SiteExtension transient failure

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AzureIntegration#144]
It seems that `Microsoft.AspNetCore.AzureAppServices.SiteExtension` is drawing from NuGet rather than an artifact dependency on the local build of `Microsoft.AspNetCore.AzureAppServices.HostingStartup`. This causes random failures on the CI when the new version of the package isn't available quite yet.

This causes instability in preview1 release builds, so please prioritize accordingly.

**Comment by ryanbrandenburg** [comment]
I saw this still today: http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=403491&_focus=374

**Comment by pakrym** [comment]
Should be fixed by https://github.com/aspnet/Universe/commit/9f68d4b92ec6d0cfa9414decd0b6f391a05167c1 that build in http://aspnetci/viewLog.html?buildId=403543&buildTypeId=Releases_21Public_SiteExtension&tab=buildChangesDiv
