### ISSUE TITLE
Site extension names are confusing

### ISSUE THREAD

**Issue by danroth27** [aspnet/AzureIntegration#161]
Currently we have two site extensions for ASP.NET Core: 
- ASP.NET Core Extensions
- ASP.NET Core Runtime Extensions

No one can figure out which one to use or what they do. Can we clarify the names? Can we add a descriptive text that shows up in the portal?

@glennc @shanselman

**Comment by shanselman** [comment]
Can we just toss one? Or make Extensions into "Logging" TODAY?

**Comment by pakrym** [comment]
Renamed `ASP.NET Core Extensions` to `ASP.NET Core Logging Extensions` as part of https://github.com/aspnet/AzureIntegration/issues/227
