### ISSUE TITLE
Site Extension Experience is not good when used with Slots

### ISSUE THREAD

**Issue by graemechristie** [aspnet/AzureIntegration#163]
Currently, If we install the ASPNet Core 2.1 preview1-final Site Extensions using a resource template, or manually add a template via the Portal UI, the site extension will be removed the next time we deploy to a slot (using the Azure Powershell commandlets) and swap that slot into the production slot (using the Azure Powershell commandlets).

As we do all of our deploys automatically, from CI, we cannot manually add a site extension after every deploy. 

We currently need to re-add the site extension using a [hacky script](https://stackoverflow.com/questions/43693245/how-to-add-an-azure-app-service-extension-via-powershell) 

Currently, using slots and CI to deploy to Azure App Services feels like a very second class experience.

Is the site extension method just required as this is a preview release ? Or are we going to need to jump through these hoops for the full release ?

Could we consider moving to a process of using app settings rather than site extensions as the PHP/Python/.NET FF engines do ?

**Comment by Tratcher** [comment]
Which extension? There are two. The Runtime extension is intended only use with previews.

**Comment by graemechristie** [comment]
Yes, the Runtime extension. If it is only for previews then that is ok. Thanks for the information. I coudnt find any information stating that this would  be required once 2.1 final was released.
