### ISSUE TITLE
Investigate AI hosting startup runtime store for netcoreapp2.1/aspnetcore2.1

### ISSUE THREAD

**Issue by pakrym** [aspnet/AzureIntegration#165]

**Comment by muratg** [comment]
@glennc Is there an AI bug tracking this for the next milestone?  If not, could you file?

**Comment by pakrym** [comment]
https://github.com/dotnet/core-setup/issues/3884

**Comment by pakrym** [comment]
We decided to try AssemblyLoadContext idea for implementing hosting startups.

**Comment by muratg** [comment]
cc @natemcmaster

**Comment by natemcmaster** [comment]
> We decided to try AssemblyLoadContext idea for implementing hosting startups.
Should this be assigned to me to investigate? or are you also going to try building an implementation @pakrym ?

**Comment by Eilon** [comment]
@natemcmaster / @pakrym / @muratg - is this a must-have for Preview2? If not, let's move to RC1.

**Comment by natemcmaster** [comment]
Move to RC1. No work planned for preview2 on this

**Comment by natemcmaster** [comment]
Initial prototype for using AssemblyLoadContext is here: https://github.com/aspnet/Hosting/tree/namc/alc

We think this is something we want to pursue, but it coordination with the dotnet team. There is enough assembly-loading, deps.json-parsing, rid-graph-defining stuff in it that it would be fragile for us to own this completely right now. It's unlikely we can get all of this in for 2.1.0-rc1. Re-marking as "1 - Ready" for now as I'll work with @glennc to kick off those conversations, but for now, prototyping and playing with ALC is done.

In the meantime, we need to get fixes to additionalDeps to enable the AI hosting startup features in 2.1.

**Comment by natemcmaster** [comment]
I've unassigned myself from this. There is no action currently planned for this.

**Comment by muratg** [comment]
@davidfowl I've backlogged this one. If you care about it, let me know.

**Comment by pakrym** [comment]
I don't think this issue is actionable at this point. Closing.
