### ISSUE TITLE
'Microsoft.AspNetCore.AzureKeyVault.HostingStartup 2.0.2-preview1-final' package install displays a warning because a dependency version was not found

### ISSUE THREAD

**Issue by prasethu** [aspnet/AzureIntegration#169]
Configuration: 
OS: RS4 17632 x64
VS: d15.7/27525.3005

More info:
The bug will be gone if you install Microsoft.AspNetCore.Hosting.Abstractions( >=2.0.1) as the prompted manually.

Steps to reproduce:  
Create a ASP.NET Core 2.0 project
Open Connected Services tab
Click Secure Secrets with Azure Key Vault
Click Add button to add Key Vault to project
Actual: Below warning after installed Key Vault:

Microsoft.AspNetCore.AzureKeyVault.HostingStartup 2.0.2-preview1-final depends on Microsoft.AspNetCore.Hosting.Abstractions (>= 2.0.1-rtm-105) but Microsoft.AspNetCore.Hosting.Abstractions 2.0.1-rtm-105 was not found. An approximate best match of Microsoft.AspNetCore.Hosting.Abstractions 2.0.1 was resolved.

Expected:
No any warning after installed Key Vault provider.

**Comment by muratg** [comment]
cc @danroth27 @glennc @natemcmaster

**Comment by pakrym** [comment]
Yep, it got build against 2.0.1-rtm-105 dependencies. I'll rebuild it correctly after fixing https://github.com/aspnet/AzureIntegration/issues/160

**Comment by pakrym** [comment]
@muratg using this to track producing new preview keyvault package.

**Comment by muratg** [comment]
@pakrym good to close?

**Comment by Eilon** [comment]
@pakrym / @muratg - is there more action to take for Preview2? If not, let's close or move to RC1.
