### ISSUE TITLE
Spike lighter App Insights integration for VS

### ISSUE THREAD

**Issue by glennc** [aspnet/AzureIntegration#175]
We want to enable the in-VS experiences like CodeLens and the search window, but adding the full app insights SDK right now has some unfortunate side effects. These effects, like injecting `HttpContextAccessor`, are somewhat unavoidable when you want deep integration with ASP.NET Core for full telemetry.

However, we think there is a subset of data used by VS that we could instead get by have by hooking the various diagnostic sources in the ASP.NET Core (e.g. in hosting and MVC) and an `ILoggerProvider` that all push data to the debug log in the same JSON format that the in-VS experience expects (basically the `Telemetry` object serialized to JSON). If we do that then the impact on the app is minimal, and restricted to areas that are more resilient to injection and change. We should spike out proving that we can do this and how much of the VS experience, if any, we have to sacrifice with this lighter dependency.

**Comment by glennc** [comment]
This isn't really the right repo for this, but it's close as I could think of for now.

**Comment by JunTaoLuo** [comment]
Is this more or less the tracking issue for https://gist.github.com/glennc/131987315a073d5cb15f76212c586035 @glennc ?

**Comment by JunTaoLuo** [comment]
Is this still something we want to do?

**Comment by muratg** [comment]
@glennc closing this as we're prepping for the mondo repo. If you still care about it, please ping me or file an issue in aspnetcore repo.
