### ISSUE TITLE
Diagnostic log settings are not reloaded when changed from portal

### ISSUE THREAD

**Issue by pakrym** [aspnet/AzureIntegration#177]
When using preview2 AppServices site extension. 
Reproes both on x86 and x64 runtimes.

**Comment by muratg** [comment]
@pakrym could you take the initial look?

**Comment by muratg** [comment]
@pakrym were you able to find any workaround?

**Comment by pakrym** [comment]
Restarting the app.

**Comment by muratg** [comment]
@pakrym status?

**Comment by pakrym** [comment]
In progress, maybe, it's harder than I though.

**Comment by muratg** [comment]
@pakrym Close??

**Comment by pakrym** [comment]
Not yet, there wasn't able to verify with new site-extension yet.
