### ISSUE TITLE
Microsoft.AspNetCore.AzureKeyVault.HostingStartup should include Build from it's dependency on Microsoft.Azure.Services.AppAuthentication

### ISSUE THREAD

**Issue by prasethu** [aspnet/AzureIntegration#186]
There is a scenario we’ve identified that can block certain users from accessing their Key Vaults. Let me explain:

The way it works is that the ASAL extension in VS on load creates a file that is necessary for the ASAL libraries to work – which is responsible for authenticating with Azure. This file is created on VS first launch and upgrade scenarios. But in certain cases, we’ve seen users missing this file and thereby blocking them from accessing Key Vault.

The ASAL extension in VS only loads when a project capability “AzureTokenProvider” is available in the currently loaded project (more common) OR if you go to Tools Options and access the “Azure Service Authentication” page. 

The project capability “AzureTokenProvider” is proferred by the nuget package “Microsoft.Azure.Services.AppAuthentication” which is listed as a dependency on “Microsoft.AspNetCore.AzureKeyVault.HostingStartup”. The issue is that the ASAL extension in VS does not load to create the file for the ASAL libraries to use because the project capability is not available in the project because of the way the HostingStartup package lists the dependency on the AppAuthentication package – which prevents the target file that has the project capability from being available to the project.

The request is to update the dependency on AppAuthentication from:

        <dependency id="Microsoft.Azure.Services.AppAuthentication" version="1.1.0-preview" exclude="Build, Analyzers" />

To

        <dependency id="Microsoft.Azure.Services.AppAuthentication" version="1.1.0-preview" include="Build" exclude="Analyzers" />

**Comment by natemcmaster** [comment]
Can be fixed by `PrivateAssets="None"` to this package reference. https://github.com/aspnet/AzureIntegration/blob/a926239281dba7fd83404e321e8ce263569c68f7/src/Microsoft.AspNetCore.AzureKeyVault.HostingStartup/Microsoft.AspNetCore.AzureKeyVault.HostingStartup.csproj#L17
