### ISSUE TITLE
Please consider adding none iis azure deployments

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/AzureIntegration#2]
please adding functionality for none iis azure deployment like kestrel on nanoserver/linux etc.

**Comment by halter73** [comment]
@grahamehorner We have [linux production guidance](https://docs.asp.net/en/latest/publishing/linuxproduction.htm) which recommends using a reverse proxy like nginx.

We also have [guidance for Nano Server](https://blogs.iis.net/adminapi/microsoft-iis-administration-on-nano-server) that uses IIS with ANCM.
