### ISSUE TITLE
Update version of Microsoft.ApplicationInsights.AspNetCore

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AzureIntegration#20]
This dependency depends on Hosing 1.0.0, we will need to update to a new version that targets our 2.0.0 packages.

**Comment by glennc** [comment]
AppInsights feed https://www.myget.org/F/applicationinsights/api/v3/index.json

There is a 2.1.0-beta2 available there now. @JunTaoLuo @muratg Presumably we need to get this ingested now if it goes in the store.

**Comment by Eilon** [comment]
@kichalla - is this something we can mirror in our mirror task? I don't want to add a dependency on another team's MyGet feed from within this repo.

**Comment by kichalla** [comment]
Yes we can add it.

**Comment by kichalla** [comment]
It's part of the mirror now. So we can probably close this issue.

**Comment by Eilon** [comment]
It's worth noting that the original thing @JunTaoLuo mentioned is this:

> This dependency depends on Hosing 1.0.0, we will need to update to a new version that targets our 2.0.0 packages.

And this new mirroring doesn't fix that. However, that's ok - we don't need AppInsights to update their Hosting dependency.

But, to close this issue, we need to actually update the code in this repo to use the new AppInsights packages.

**Comment by Eilon** [comment]
Assigning to @pakrym for Preview1.

**Comment by DamianEdwards** [comment]
Do we have a plan in place to ingest updates?

**Comment by Eilon** [comment]
And actually, even after taking that new dependency, let's keep this bug open, because we need to wait for the final build of App Insights RTM as well for Preview 1.

**Comment by DamianEdwards** [comment]
*snap*

**Comment by DamianEdwards** [comment]
FYI there is an issue with the 2.1.0-beta2 package: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/416

**Comment by pakrym** [comment]
Fixed by https://github.com/aspnet/AzureIntegration/pull/46
