### ISSUE TITLE
Update runtime site extension to set DOTNET_ROOT

### ISSUE THREAD

**Issue by shirhatti** [aspnet/AzureIntegration#208]
If we don't set DOTNET_ROOT in the runtime site extension, framework dependent exes will break.

**Comment by shirhatti** [comment]
cc @pakrym

**Comment by muratg** [comment]
@pakrym thoughts on this? Is this broken?

**Comment by pakrym** [comment]
This feature (framework dependent exes) was broken in 2.2 and wasn't enabled by default so we are not terribly broken but it's still nice to have.
