### ISSUE TITLE
Solved: Gateway problem in Azure

### ISSUE THREAD

**Issue by lautarogalancid** [aspnet/AzureIntegration#209]
Thanks for reading. I'm completely new to Azure, so bear with me, please. I'm pretty sure this is an absolute novice question, but here it goes:

I've done an ASP.Net Core 2 API, which connects to Google Drive, reads a spreadsheet, and returns the data in a JSON. **This works great in my local IIS Express server** (Launching it from VS), but now they ask me to upload this to an Azure, and here's where I get the following error:

> Code 502: Error: Bad Gateway The specified CGI application encountered an error and the server terminated the process.

I have no idea why this is happening. I tried configuring the Azure App in different ways but nothing works. I'm assuming this is an Azure problem since the app works when running locally.

I looked in the Azure's diagnostic and it reads: ASP.NET Core startup failure detected

> Application 'MACHINE/WEBROOT/APPHOST/API-LG' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\LG-API.dll', ErrorCode = '0x80004005 : e0434352. 

I tried searching for different answers but nothing really works, or sometimes I don't really understand what they're saying since I'm an absolute novice in Azure.

Forgot to mention: The api worked fine before i added the google sheets API in the mix (which came in replacing what it used to do)

Could you guys set me on track?

**Comment by Praefectus-praetorio** [comment]
I've got exactly the same issue. .NET Core 2.0 with Google Sheets API on Azure:
Code 502: Error: Bad Gateway The specified CGI application encountered an error and the server terminated the process.

Locally it works like a charm. Could you please help?
