### ISSUE TITLE
Azure App Sites siteextension work

### ISSUE THREAD

**Issue by muratg** [aspnet/AzureIntegration#21]
- Add siteextension project to the repo
- Build with CI 

cc @glennc

**Comment by glennc** [comment]
https://github.com/glennc/site_extension

**Comment by Tratcher** [comment]
Consider putting it in the https://github.com/aspnet/MetaPackages repo (or its own repo) instead, as the site extension primarily depends on the output of the package cache metapackage. The site extension does not directly depend on any of the components in this repo.

**Comment by Tratcher** [comment]
Name: Microsoft.AspNetCore.AzureAppServices.SiteExtension
Docs:
https://azure.microsoft.com/en-us/blog/azure-web-sites-extensions/

**Comment by Tratcher** [comment]
https://azure.microsoft.com/en-us/blog/writing-a-site-extension-for-azure-websites/

**Comment by Tratcher** [comment]
Initial checkin and packaging complete. Xdt.Extensions needs tests.

**Comment by muratg** [comment]
Will add tests in preview2.

**Comment by Tratcher** [comment]
@muratg  this can move to preview3, we're not updating the extension for preview2.

**Comment by muratg** [comment]
Remaining work for 2.0.0: Tests.
