### ISSUE TITLE
Adding ASP.NET Core 2.2 Runtime site extension to multiple web apps in same resource group fails due to not enough space on disk

### ISSUE THREAD

**Issue by balachir** [aspnet/AzureIntegration#221]
### Scenario : 

1. Clean machine with 15.9 Preview 2 + .NET Core 2.2 Preview 2 installed. 
2. Create new ASP.NET Core 2.2 (.NET Core) web app > Empty or Web App (MVC) template 
3. F5 
4. Publish to Azure
5. Add the "ASP.NET Core 2.2 (x86) Runtime" site extension following the instructions from [the documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#deploy-aspnet-core-preview-release-to-azure-app-service) or using Kudu site extensions (to workaround issue #220)

### Repro Steps : 
- Repeat the above steps (especially 4 and 5) a few times, while publishing to the **_same resource group_** each time.

### Issue : 
Adding the site extension fails with "Not enough space on disk"
![image](https://user-images.githubusercontent.com/8246794/45668808-f02a4280-bad2-11e8-83b3-961d8d3706db.png)

### Workaround :
I need to publish the web app to a different resource group to be able to add the site extension successfully

**Comment by muratg** [comment]
In 2.2, we'll remove SDK from the siteextension. This will be a smaller issue then.
