### ISSUE TITLE
After ASP.NET Core 2.2 site extension has been added to web app on Azure, need to wait a long time after web app restart to be able to view the site successfully

### ISSUE THREAD

**Issue by balachir** [aspnet/AzureIntegration#222]
### Scenario : 

1. Clean machine with 15.9 Preview 2 + .NET Core 2.2 Preview 2 installed. 
2. Create new ASP.NET Core 2.2 (.NET Core) web app > Web Application (MVC) template 
3. F5 
4. Publish to Azure
5. Add the "ASP.NET Core 2.2 (x86) Runtime" site extension following the instructions from [the documentation](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#deploy-aspnet-core-preview-release-to-azure-app-service) or using Kudu site extensions (to workaround issue #220)

### Repro Steps : 
After site extension has been added successfully, restart the site on the portal
![image](https://user-images.githubusercontent.com/8246794/45669790-f0780d00-bad5-11e8-9c73-e25bcc2382e4.png)

Try to view the published web app from the browser

### Issue : 
Page still does not load. You continue to get the error below
![image](https://user-images.githubusercontent.com/8246794/45669907-48af0f00-bad6-11e8-89aa-832c814cce42.png)

### Workaround :
Need to wait for about 10 - 15 minutes, then restart the site again. Then the page loads fine.
![image](https://user-images.githubusercontent.com/8246794/45669946-5d8ba280-bad6-11e8-81f3-757b1277a142.png)

**Comment by muratg** [comment]
@balachir any other info on this? Were you able to repro again? We have never seen this happen in our experiments.

**Comment by balachir** [comment]
@muratg the CTI team and I did some more investigation on this issue. It seems to reproduce only when you hit the "Restart Site" button in the Kudu "Site Extensions" tab. I've opened issue https://github.com/projectkudu/kudu/issues/2888 on Kudu. Closing this one.
