### ISSUE TITLE
Pre-release version of Microsoft.AspNetCore.AzureAppServices.SiteExtension gets enabled by default when publishing an ASP.NET Core 2.1 app to Azure from VS 15.8 

### ISSUE THREAD

**Issue by balachir** [aspnet/AzureIntegration#223]
### Scenario : 

1. Clean machine with 15.8
2. Create new ASP.NET Core 2.1 (.NET Core) web app > Web Application (MVC) template 
3. F5 
4. Publish to Azure with default selections (Install "ASP.NET Core site extension" is checked in the Publish settings tab)

![image](https://user-images.githubusercontent.com/8246794/45672753-cf1b1f00-badd-11e8-80e4-6e131cebad9f.png)

### Repro Steps : 
Site extension gets enabled on the Azure web app after publishing
![image](https://user-images.githubusercontent.com/8246794/45673046-86179a80-bade-11e8-8a66-eedf049cb60d.png)

### ACTUAL
Version of the ASP.NET Core Extensions site extension is **2.1.0-preview2-final**

### EXPECTED
As I'm publishing ASP.NET Core 2.1 app from 15.8 (RTW product), I would expect that the version of the site extension that gets enabled by default is not a pre-release version.

**Comment by pakrym** [comment]
Currently, this is by design

@glennc

**Comment by muratg** [comment]
@glennc What's your thoughts on this? Good design? Should we change the design?

**Comment by balachir** [comment]
When I tried the above repro steps again now, it looks like the version of **ASP.NET Core Extensions** has been updated to **2.1.1**. So I think we can go ahead and close this issue now. 


![image](https://user-images.githubusercontent.com/8246794/47001891-64f79900-d0e0-11e8-9d93-960cfc54fbeb.png)

**Comment by muratg** [comment]
Thanks Bala!
