### ISSUE TITLE
IHostingStartup support for multiple key vaults

### ISSUE THREAD

**Issue by bjpierron** [aspnet/AzureIntegration#236]
The IHostingStartup implementation for key vault in ASP.NET Core appears to support a single key vault configuration. I would like to retrieve secrets from an application specific key vault, as well as a more general shared key vault. An example of a shared secret might be a SendGrid API key. Is IHostingStartup support for multiple key vaults on the roadmap, or is the use of multiple key vaults in this way discouraged?
Thanks!

**Comment by pakrym** [comment]
You can use AddAzureKeyVault (https://github.com/aspnet/Configuration/blob/d469707ab18eef7ed0002f00175a9ad5b0f36250/src/Config.AzureKeyVault/AzureKeyVaultConfigurationExtensions.cs#L134 ) extension method multiple times but I don't think support for multiple keyvaults via hosting startup is planned.
