### ISSUE TITLE
Change default location of ANCM debug logs in site extensions

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AzureIntegration#242]
Based on docs conversation: https://github.com/aspnet/Docs/pull/9180#discussion_r227580128, we should remove the value attribute which would change the default log location to %HOME%\LogFiles\aspnetcore-debug.log. https://github.com/aspnet/AzureIntegration/blob/master/extensions/Microsoft.AspNetCore.Runtime.SiteExtension/applicationHost.xdt#L13. Also amcm is misspelled, but that will be removed 😄

**Comment by pakrym** [comment]
That file is not used anymore and debug setting is removed:  https://github.com/aspnet/AspNetCore/blob/master/src/SiteExtensions/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/applicationHost.xdt
