### ISSUE TITLE
Add back UseIISIntegration until ANCM is updated and deployed

### ISSUE THREAD

**Issue by glennc** [aspnet/AzureIntegration#35]
UseAzureAppServicesIntegration should still call UseIISIntegration until we have updated ANCM

**Comment by muratg** [comment]
@shirhatti what should we do about this bug?

**Comment by shirhatti** [comment]
Call `.UseIISIntegration()` till we have confirmation that from @davidebbo that the latest ANCM (1981) has finished deploying in all regions.

**Comment by muratg** [comment]
So do we keep it in for Preview2? (Which we're trying to close and go into escrow by tomorrow)

**Comment by shirhatti** [comment]
Yes. Keep the call.
@Tratcher can confirm that the call to `.UseIISIntegration()` is idempotent, so I wouldn't mind a duplicate call as opposed to relying on the deployment to go out in time for preview2

**Comment by Tratcher** [comment]
Yes it's idempotent.

**Comment by muratg** [comment]
Removing bugs from 2.0.0 milestone. This is risky in a sense that hosters with the previous ANCM deployments would be broken with this update.

**Comment by pakrym** [comment]
I don't think this issue is relevant anymore.
