### ISSUE TITLE
Have the build set license, icon, and project urls for SiteExtension

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AzureIntegration#38]
https://github.com/aspnet/AzureIntegration/issues/32
AzureAppServices.SiteExtension is a package we do not ship to nuget.org, it goes to the site extension gallery instead. Because it's marked as no-ship, the build does not stamp it with standard attributes like licenseUrl, iconUrl, and projectUrl. These have been hardcoded for now, but we should update the build to accommodate this package. We have a similar problem with signing (https://github.com/aspnet/Coherence-Signed/issues/453).

**Comment by Tratcher** [comment]
We also have to change the build so that the nuspec does not have the `serviceable` or `repository` attributes. SiteExtensions.net uses an old version of nuget (2.8?) that does not allow extra properties beyond the schema. We may just have to build the package directly from a hardcoded nuspec.

**Comment by muratg** [comment]
Manually done for preview1. Will automate in preview2.

**Comment by natemcmaster** [comment]
Some properties KoreBuild sets that may help with automating the licence URL: `$(GitBranch)`, `$(CommitHash)`, `$(VersionPrefix)`

**Comment by Tratcher** [comment]
@muratg this can move to preview3, we're not updating the extension for preview2.

**Comment by Eilon** [comment]
BTW the URLs currently used in the site extension are HTTP, but they should be HTTPS. However we do this work, let's make sure it's the HTTPS URLs (which are available).

**Comment by muratg** [comment]
We won't be doing another deployment to siteextensions.net for 2.0.0 as per the POR. Moving this out to 2.1.

**Comment by Tratcher** [comment]
This is unblocked now. Azure is updating their site extensions infrastructure such that we can build these as normal up-to-date nupkg's. Changing the category from shipoob to ship should take care of most of these issues.

**Comment by Eilon** [comment]
cc @natemcmaster because the categorization stuff is changed/changing. Be careful about 'ship' because this isn't in the metapackage and doesn't match other criteria for things that "ship," even though this does now go to NuGet.org.

**Comment by Tratcher** [comment]
what criteria? inclusion in the metapackage is a different flag.

**Comment by muratg** [comment]
Yup, see this: https://github.com/aspnet/Universe/blob/dev/build/artifacts.props 

Though I agree with @Eilon that we should take a look to see if this affects other things (perhaps the LZMA?)

**Comment by Eilon** [comment]
I don't know how this stuff works now (or before, really), but I want to make sure we don't cross any streams because we really don't want to get this wrong. What's worse, if we get it wrong in certain ways, we'd likely never notice until it's too late.
