### ISSUE TITLE
Feature Request: ANCM logging activation in the portal/package

### ISSUE THREAD

**Issue by GuardRex** [aspnet/AzureIntegration#4]
I worked through another app startup issue on Slack that required activation of the ANCM logging with an Azure App. Is it on the roadmap to add a switch in the Azure App's Diagnostics logs panel and bits to the package that will allow devs to flip a switch and get ANCM logging without having to update `web.config` (and perhaps even without having to set the log path)?

**Comment by muratg** [comment]
That's a cool idea. @shirhatti What do you think? Who do we need to follow-up internally for this?

cc @DamianEdwards

**Comment by DamianEdwards** [comment]
When you say "ANCM logging", do you just mean its ability to capture stdout from the launched process and write that to a file? If so, that also requires the app to be have the console logger configured (in the app's code), making this a little more challenging. It's not impossible mind you, and we are investigating ways of allowing application hosts (like Azure) configure aspects of the `WebHost` during app start without anything having to be in the application at all. This could be a good candidate for something that could take advantage of that.

**Comment by Tratcher** [comment]
This may also be a good place to implement a timeout that automatically turns the logging off. Not to mention having a simple way to delete the logs when you're done.

**Comment by GuardRex** [comment]
The app doesn't require console logging when the ANCM fails to start the process and logs, correct? There is a class of exceptions that the ANCM can trap and report merely if the `stdoutLogEnabled` is enabled with a correct log path for Azure Apps. Those types of things ..... bad entries in `web.config` for example ... would be helpful.

**Comment by Tratcher** [comment]
Those aren't the web.config enabled logs, those are event logs which are already captured by the portal.

**Comment by GuardRex** [comment]
If you list an incorrect DLL for a portable app in the `arguments` of `web.config`, the event log (`Event Viewer > Application Log`) shows ...
```
Application 'MACHINE/WEBROOT/APPHOST/{APP}' with physical root '{PATH}\' failed to start 
process with commandline '"dotnet" .\{app}.dll', ErrorCode = '0x80004005 : 80008081.
```
That's fine, but that doesn't really tell you what you did wrong.

If you enable `stdoutLogEnabled="true"`, you get the stdout log, and it will show ...
```
The application to execute does not exist: '{PATH}\bad_application_DLL_name.dll'
```
It doesn't require console logging to be setup in the app. There are probably only three helpful cases currently ...

Problem | Entry
--- | ---
Bad DLL entry | The application to execute does not exist: 'PATH\my_application.dll'
Platform/RID conflict | Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'my_application.dll'. An attempt was made to load a program with an incorrect format.
Missing .NET Framework | Missing method, file, or assembly exception. The method, file, or assembly specified in the exception is a .NET Framework method, file, or assembly.

:point_up: There might be some opportunities to expand that, and I mean outside of console logging. Try to grab anything helpful when a process fails to start and supply any possible guidance to the dev that the ANCM can determine.

Do we need this issue open? I think you prob have an internal Azure issue tracking, correct? If you plan to have console logging piped in there somehow, my OP suggestion will be covered by it.

**Comment by shirhatti** [comment]
> Is it on the roadmap to add a switch in the Azure App's Diagnostics logs panel and bits to the package that will allow devs to flip a switch and get ANCM logging without having to update web.config

Have a look at the [Azure App Service logging provider section](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/) in this blog post.

> This may also be a good place to implement a timeout that automatically turns the logging off

If I'm not mistaken, production logging in the portal automatically turns off after a fixed timeout.
