### ISSUE TITLE
Unskip ApplicationInsightsLoggingTest.ScriptInjected

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AzureIntegration#41]
Test was skipped to unblock build.  I suspect the fix is for AzureIntegration to react to https://github.com/aspnet/Hosting/commit/3936bf64f6edf8a1e3cca8f6e248f60c073b312d.

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/aspnet/AzureIntegration/pull/33
