### ISSUE TITLE
Don't force lift dependencies in Microsoft.AspNetCore.ApplicationInsights.HostingStartup

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AzureIntegration#45]
Figure out what to do in `Microsoft.AspNetCore.ApplicationInsights.HostingStartup`, the `Microsoft.ApplicationInsights.AspNetCore` package currently targets `1.0.0` of our stuff, this can cause issues which is why we lifted dependencies in this package.

**Comment by muratg** [comment]
Won't be able to do this due to Razor reference.
