### ISSUE TITLE
Getting Information messages when set to Warning.

### ISSUE THREAD

**Issue by runxc1** [aspnet/AzureIntegration#5]
I have an Azure website that is running on Asp.Net Core 1.1.   The site is using the Extension "UseAzureAppService" (see below) to set up logging.   On the web application I have been able to turn on the "Application Logging(Blob)" under the Diagnostic logs and have set the level to warning.   The only problem is the log file is getting flooded by Information messages.   Is this an error in the code or something I haven't set up correctly?

```
         public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseAzureAppServices()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

**Comment by runxc1** [comment]
It appears that I am not the only one getting this Issue as it appears related to this issue

https://github.com/aspnet/Logging/issues/517

**Comment by muratg** [comment]
@pakrym Could you investigate? If there's a bug, this is possibly a 1.1.1 fix.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.
