### ISSUE TITLE
HostingStartup light-up changes AKA detectoid

### ISSUE THREAD

**Issue by anurse** [aspnet/AzureIntegration#54]
A few proposed changes to HostingStartup after some discussions with Damian:

1. Add HostingStartup packages to Microsoft.AspNetCore.All
2. Make HostingStartup packages reference their dependencies with `PrivateAssets=compile` to avoid exposing the APIs unintentionally (side note: verify that manually referencing the package **does** bring in the APIs)
3. For each HostingStartup package, build a "detectoid" DLL which determines if a particular HostingStartup should be applied to an app.

Detectoid DLLs are `netstandard2.0` DLLs that sit next to the hosting startup's additional deps file and can be loaded by Hosts (VS, Azure, etc.) and queried to determine if a HostingStartup should be injected into the app. We will ship an assembly containing an interface, `IHostingStartupDetector`:

```csharp
public interface IHostingStartupDetector
{
    IDictionary<string, string> DetectHostingStartup(string applicationOutputPath, string hostingStartupDepsJsonPath);
}
```

Detectoid DLLs are dlls containing a class implementing this interface. The Host would load this class, and run `DetectHostingStartup`, passing it the path to the app base and the path to the additional deps file for the HostingStartup assembly. The detectoid returns any environment variables that should be set to enable this Hosting Startup component (if it should in fact be enabled). Hosts would take these values from all detectoids they run and concatenate them, then provide them as environment variables when launching the app.

Using detectoid DLLs means that Hosts don't need to have custom logic for each HostingStartup assembly to determine if they should be activated, and the logic can be made consistent across implementations and versions.

/cc @DamianEdwards @muratg @davidfowl

**Comment by anurse** [comment]
Note for isolation: The hoster could always load the library up in an out-of-proc container of some kind (or an AppDomain in VS).

**Comment by anurse** [comment]
New thought: We ship these detectoids as NuGet packages, but not part of the runtime store or metapackage. Hosts (VS, Azure, etc.) just reference these packages directly (rather than looking for them in a magic directory).

Additionally, we could just put the additional deps files in those NuGet packages.

**Comment by muratg** [comment]
Backlogging this for now. We'll need to understand the requirement for this type of feature and possibly bring this back in a minor milestone.

cc @glennc

**Comment by muratg** [comment]
Closing this. If there's need, we'll consider again.
