### ISSUE TITLE
HostingStartup packages should reference their dependencies with PrivateAssets=compile

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AzureIntegration#55]
https://github.com/aspnet/AzureIntegration/issues/54
Microsoft.AspNetCore.ApplicationInsights.HostingStartup
Microsoft.AspNetCore.AzureAppServices.HostingStartup

**Comment by muratg** [comment]
Per the discussion https://github.com/aspnet/MetaPackages/issues/125 will be enough (where the metapackage will have the dependency with PrivateAssets=compile.)

**Comment by muratg** [comment]
We decided not to do this.
