### ISSUE TITLE
Azure Key Vault light up

### ISSUE THREAD

**Issue by danroth27** [aspnet/AzureIntegration#57]
Light up Key Vault config provider and Key Vault signing credential

Light up implementation 
-	New package in the AzureIntegration repo
-	Implement IHostingStartup that adds signing credential provider and config provider (data protection post 2.0)
-	Needs to generate deps file
-	The entire package graph then needs to ship (key vault SDK already in there)
-	Add to the meta package
-	Add hosting startup package to site extension 

Environment variable schema proposal:

ASPNETCORE_KEYVAULT_BASEURI

// These will no longer be needed once we have MSI integration
ASPNETCORE_KEYVAULT_CLIENTID
ASPNETCORE_KEYVAULT_CLIENTSECRET
ASPNETCORE_KEYVAULT_CLIENTCERTIFICATETHUMBPRINT

ASPNETCORE_IDENTITY_SIGNINGCERTIFICATEIDENTIFIER

// Feature level flags for enabling/disabling specific feature light up
ASPNETCORE_FEATURE_KEYVAULTCONFIG – turn on/off the config provider
ASPNETCORE_FEATURE_KEVAULTIDENTITY – turn on/off the signing credential provider
ASPNETCORE_FEATURE_KEYVAULTDATAPROTECTION – turn on/off data protection integration

**Comment by pakrym** [comment]
@muratg

**Comment by muratg** [comment]
@danroth27 when do we want to do this?

cc @DamianEdwards

**Comment by danroth27** [comment]
@mlorbetske  We want to do this as part of the 2.0 wave. I'd love to preview an end-to-end experience for preview2, but we would need to make available both the key vault light up piece and the key vault provisioning tooling. Realistically I think this will be post preview2.

**Comment by muratg** [comment]
cc @javiercn

**Comment by Eilon** [comment]
@muratg / @pakrym  - anything to do here for preview1?

**Comment by pakrym** [comment]
Nothing for preview1.
