### ISSUE TITLE
Site extension shows up as installed, but keeps asking to be installed with the "+" button

### ISSUE THREAD

**Issue by Eilon** [aspnet/AzureIntegration#63]
I have the ASP.NET Core site extension "installed" in my app, but the "+" button still appears, which indicates it isn't fully installed.

![image](https://user-images.githubusercontent.com/202643/27297298-252d3a8e-54d9-11e7-9388-87b5eedfd9ce.png)

Perhaps the fix would be to have the site extension have a minimal UI (even just a static HTML page) that says what it is, the version, what it's for, maybe a help link, etc.?

**Comment by DamianEdwards** [comment]
@glennc @pakrym any idea on this?

**Comment by pakrym** [comment]
It does look like Kudu UI bug. I've seen this a lot while verifying site extensions and it doesn't prevent things from working just adds a bit of confusion.

**Comment by Eilon** [comment]
Could be a Kudu UI bug. But I did also include a suggestion that might in theory work around the bug (based on all kinds of baseless assumptions I've made about how it works). Thoughts on having a static info page?

**Comment by pakrym** [comment]
The page itself is not a bad idea.
I'm just worried about the discoverability of this page.

**Comment by Eilon** [comment]
Not an urgent issue. Feel free to close.

**Comment by Eilon** [comment]
And no one else complained.
