### ISSUE TITLE
Verify that AI lightup logger filter rules is composed correctly with appsettings.json

### ISSUE THREAD

**Issue by pakrym** [aspnet/AzureIntegration#64]
Required layering:
1. AI defaults
2. AI setting.json file
3. appconfig.json

**Comment by muratg** [comment]
@pakrym status?

**Comment by pakrym** [comment]
https://github.com/aspnet/AzureIntegration/pull/69 this is part of it, we also need to get a build of AI that has https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/486 in

**Comment by muratg** [comment]
@pakrym will this be in today, or Monday?

cc @Eilon

**Comment by pakrym** [comment]
@DamianEdwards said next week

**Comment by pakrym** [comment]
Manual verification/validation part. All PR's are in but we still need to ingest AI package as soon as they produce it.

**Comment by muratg** [comment]
@Eilon This will happen Monday possibly.  cc @mikeharder as we'll need to ingest their packages.

cc @glennc to follow-up with AI folks as both @Eilon and me will be OOF.

**Comment by Eilon** [comment]
@pakrym @glennc @mikeharder - What's left here?

**Comment by pakrym** [comment]
@Eilon I was waiting for build of CLI with new AI package and out fixes to do verification on clean machine.

**Comment by Eilon** [comment]
@pakrym ok - do we know when we'll have that? I would have thought that the AI in the CLI would be done by now, no?

**Comment by pakrym** [comment]
@Eilon We have AI in VS light up bug now

**Comment by pakrym** [comment]
@Eilon we can close this and do it as part of verification. I just want to make sure things work E2E without hacks.

**Comment by Eilon** [comment]
@pakrym ok then please do so.
