### ISSUE TITLE
How to open TCP and UDP ports for asp.net core Azure Appservice deployment?

### ISSUE THREAD

**Issue by netsfx** [aspnet/AzureIntegration#79]
I've got an asp.net core app deployed to as Azure Appservice. The web pages run without issues, but on Azure, the TCP and UDP port, where the app is listening too, are unreachable from outside so that clients cannot connect. 

I cannot find any information how to resolve this. TCP 55556 and UDP 55555 must be reached from outside.

Also, I don't see any other fitting hosting opportunity I can use. E.g. Azure Cloud Service/Web Role seems not to work with asp.net core.

What can I do? How do I get the ports reachable?

ty!

**Comment by muratg** [comment]
Closing this as external - nothing to do with ASP.NET Core, but more an "AppServices" question.  

cc @davidebbo in case he has a recommendation where to file this.  My recommendation is StackOverflow.
