### ISSUE TITLE
Packaged deps.json file includes reference to internal assets

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/AzureIntegration#83]
The deps.json file bundled in Microsoft.AspNetCore.AzureAppServices.HostingStartup and Microsoft.AspNetCore.ApplicationInsights.HostingStartup includes references to Internal.AspNetCore.Sdk and Microsoft.AspNetCore.BuildTools.ApiCheck.

Solution:
Pack the deps.json file that comes from publish, not build. The publish step trims privateassets from the deps.json file.

**Comment by muratg** [comment]
Per the previous investigation, this doesn't seem like it has any impact on customer apps, so it's more of a cleanliness issue.  @JunTaoLuo If we can't get to it within 2.1, that's fine.

**Comment by natemcmaster** [comment]
@JunTaoLuo is this done in dev too?

**Comment by JunTaoLuo** [comment]
In dev it works a little differently. We do not build the deps files during shared framework generation. I believe in @pakrym's PR he was using the publish deps as well: https://github.com/aspnet/BuildTools/commit/b56c36c46122915b86d56836e089d7e6b57838a8
