### ISSUE TITLE
Release a stable Microsoft.Web.Xdt.Extensions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AzureIntegration#85]
Microsoft.Web.Xdt.Extensions is shared with Application insights and bundled into both ours and their site extensions. They have asked us to release release a stable version, preferably to nuget.org as we don't have other hosts for stable packages.

It still needs some tests (https://github.com/aspnet/AzureIntegration/issues/21)  and has one possible bug with hiding environment variables (https://github.com/aspnet/AzureIntegration/issues/84)

**Comment by muratg** [comment]
@glennc Thoughts here? Do we want to make this a "stable, supported" package, or work with AppInsights to get them either internalize or use a submodule to get this code?

**Comment by muratg** [comment]
Based on the discussion with @glennc, we are not planning to publish this to nuget. We'll continue to hand out source/dlls.
