### ISSUE TITLE
JavaScriptSnippetTagHelperComponent breaks CSP in inline scripts require nonce

### ISSUE THREAD

**Issue by martincostello** [aspnet/AzureIntegration#88]
I am in the process of upgrading a website to ASP.NET Core where I use a Content Security Policy that requires inline JavaScript to add a `nonce-...` attribute into the `<script>` tags because `unsafe-inline` is disallowed by the CSP to match a HTTP response header value for the current request.

The new `JavaScriptSnippetTagHelperComponent` dependency which is registered violates this as it does not provide a mechanism to add a nonce to the `<script>` tag that is generated.

Whilst this is fine per-se as this is an advanced feature, the problem is that there is no supported way to disable this feature in the Application Insights options, i.e. there is no way for an integrator to opt-out of the tag helper to render the script themselves.

As far as I can see, the only work around I have is to manually de-register the dependency added by `ApplicationInsightsStartupLoader` in my startup class, or not use the Azure integration package at all.

Is there an argument for some additional configuration options to allow for an opt-out to this behaviour?

**Comment by muratg** [comment]
@pakrym will take a look into this while working on KeyVault light-up.

**Comment by davidfowl** [comment]
@pakrym can you file the appropriate issue on app insights?
